### ISSUE TITLE
Assign value to error on interceptors

### ISSUE THREAD

**Issue by iamgbayer** [alex-cory/use-http#109]
Hi guys,

I would like to know if makes sense this possibility of assigning a value to the error on interceptors, see an example;

I need to apply a normalize function called callable depending on the type that is in types

This function would be applied before because of the data from `useFetch` destructuring should already have this value normalized.

The `useFetch` already has a possibility to set errors like the `setError` example below?

```js
const { get, error, loading, data, abort } = useFetch(types[type].url,  {
    headers: getHeaders(types[type].id),
    loading: true,
    interceptors: {
      response: data => {
        try {
          types[type].callable(data)
        } catch(error) {
          setError(error)
        }
      }
    }
  }
)
```

**Comment by alex-cory** [comment]
why not. I think that's a pretty interesting idea. It would probably need to look something like this though:
```jsx
const { get, error, loading, data, abort } = useFetch(types[type].url,  {
    headers: getHeaders(types[type].id),
    loading: true,
    interceptors: {
      response: ({ data, setError }) => {
        try {
          types[type].callable(data)
        } catch(error) {
          setError(error)
        }
      }
    }
  }
)
```
I need to think about this some more.

**Comment by alex-cory** [comment]
Okay, with the publish of `v0.1.91`, you can now do this. To set the error, just `throw` inside of the response interceptor and it will set the `error` variable.
```jsx
const App = () => {
  const options = {
    interceptors: {
      response: (response) => {
        if ([422, 402].includes(response.status)) throw Error('some error you want')
        if (!response.ok) throw Error('some error you want')
        if (response.data) response.data = toCamel(response.data)
        return response
      }
    }
  }
  return <Provider url='some url' options={options}><RestOfApp /></Provider>
}

const RestOfApp = () => {
  const { loading, error } = useFetch({ onMount: true })
  return (
    <>
      {error && error.message} {/* <-- this error will be set if a 422 or 401 happens */}
    </>
  )
}
```
I'm going to close this because I think it solves what you are trying to accomplish. If this is not what you were looking for, feel free to reopen this issue.
