### ISSUE TITLE
Async response

### ISSUE THREAD

**Issue by mrtnpro** [alex-cory/use-http#118]
https://codesandbox.io/embed/usefetch-provider-requestresponse-interceptors-tg56u

@alex-cory I'm quite sure this is not necessarily a bug but rather conceptual issue I've run into:
Weirdly, the first time an async request fires my `console.log(response)` (`L16`) returns an empty object `{}`. Only if I run the request again I'll get the actual `Response`. Could you lead me in the right direction on how to retrieve the response once it's here and do something with it?

**What I'm trying to achieve:** 
Our API provides an endpoint for submitting form data.
Now if server-side validation fails, the response will have the exact same keys as my request payload had, except there will be error messages as values. If there are errors, the response status code will be 400. Now what I'm trying to do is to somehow find out if `!response.ok` or `response.status === 400` (from the response), so I can map potential errors to actual error components in my UI. 

I've seen similar issues (accessing response from fetch) but I'm not sure why I would need an interceptor in this case.

**Comment by alex-cory** [comment]
I will take a look at this in the morning. This sounds like a bug, even though the tests are working...
The `Response` you are seeing after you click a 2nd time, is a stale `Response` object in your `async handleClick` from the 1st request you made.

Just for reference, the `response` is initially set to an empty object `{}` by default. Before the request is made, in order to avoid having to do `if (response && response.ok)` I just made `response === {}` by default.

**Comment by alex-cory** [comment]
Just an update, I think I found a solution 
![](https://media1.giphy.com/media/7eAvzJ0SBBzHy/giphy.gif)

**Comment by alex-cory** [comment]
ok, it's fixed! Please update to `v0.1.92`. If you want to see what I did, you can check out the [PR here](https://github.com/alex-cory/use-http/pull/119/files). I used a `Proxy` so that when you do `response.ok` it will actually convert to the code `response.current.ok`. That was the problem! `response.current` was being passed instead of `response`. I didn't like the `response.current.ok` syntax so I just made it so you can do `response.ok`.

**Comment by alex-cory** [comment]
Closing this, if the issue persists, please reopen the issue!

**Comment by mrtnpro** [comment]
@alex-cory wow, thanks for the super fast reply 🙂

I updated my [codesandbox example](https://codesandbox.io/s/usefetch-provider-requestresponse-interceptors-nnrif) with more detailed comments. I'm afraid the above-described issue still persists. Correct me if I'm wrong but shouldn't `L21` return the native `Response` instance? 

Unfortunately, I can't reopen this issue.

**Comment by alex-cory** [comment]
can you try changing `L21`
from:
```js
console.log("response", response)
```
to the following
```js
console.log("response.ok", response.ok)
console.log("response.body", response.body)
console.log("response.status", response.status)
console.log("response", response)
```
from this, you will see what the output below is:
also, don't forget, you can always look inside the Proxy object.
![image](https://user-images.githubusercontent.com/5455859/66930168-ca20fa00-f066-11e9-822b-f88c6241ba5b.png)

**Comment by alex-cory** [comment]
Okay, I also see the `res.json()` bit. So the reason that is happening is because `res.json()` can only be called once, which is happening internally in `useFetch`. One way to solve this, would be to make a custom `Response` object, that mimicked the actual `Response`. Another would be to, in the Proxy check for when the `key === 'json'` or one of the other `Responses` methods, and if it is, just... 🤔 still thinking/tinkering

**Comment by alex-cory** [comment]
This works
```jsx
import React from "react";
import { render } from "react-dom";
import { Snowflakes, Button, Center } from "./components";
import { useFetch } from "use-http";

import "./styles.css";

const TestUseFetch = () => {
	const { get, loading, error, data, response, ...rest } = useFetch(
		"https://reqres.in/api"
	);

	const handleClick = async () => {
		const req = await get("/user/2");
		const res = await fetch("https://reqres.in/api/user/2")
		console.log('RES: ', res)
		const res2 = res.clone()
		console.log('RES 2: ', res2)
		const resResult = await res.json()
		console.log('RES RESULT: ', resResult)
		const res2Result = await res2.json()          // <- this is working
		console.log('RES 2 RESULT: ', res2Result) // <- this is working
                 // ^ now I just have to get it to work in the hook

		// At this point I would expect a native
		// `Response` instance where I can access
		// keys like `body`, `status` or `ok`. However
		// instead it's a proxy `Response` containing
		// a key `current` which is undefined.

		// what the proxy is doing here is converting
		// response.ok ==into==> response.current.ok
		console.log("response", response.current);
		// the reason this is breaking is because
		// response.current ==into==> response.current.current
		// which is undefined
		console.log("response.ok", response.ok);
		console.log("response.body", response.body);
		console.log("response.status", response.status);
		console.log("response", response);

		console.log("-----");

		const result = await response.json();

		console.log("result", result);

		if (response.ok) {
			// Since reponse doesn't reference the `Response` instance,
			// this will never match
			console.log("Render some success component");
		}

		if (!response.ok || response.status === 400) {
			// Since reponse doesn't reference the `Response` instance,
			// this will always match
			console.log("Map respose body to error message components");
		}
	};

	return (
		<>
			<Button onClick={handleClick}>Load Data</Button>
			{error && error.messge}
			{loading && "Loading..."}
			{data && <pre>{JSON.stringify(data, null, 2)}</pre>}
		</>
	);
};
```

**Comment by mrtnpro** [comment]
@alex-cory thanks so much for pitching in again. 

Yes, I was experimenting in my codesandbox, trying to get the response body, however, I figured I might as well get it from `req` directly.

This is what I came up with:
```
  const onSubmit = async (data) => {
    const result = await request.post('/somewhere', data)

    if (response.ok) {
      onSuccess()
    }

    if (!response.ok && response.status === 400) {
      Object.keys(result).map((value, index) =>
        setError(value, 'error', result[value])
      )
    }
  }
```

Everything's working just fine, at least for my current needs 🙂
Gotta admit you've saved me a lot of time with your fast response.
What's your PayPal, I'd love to buy you a ☕️.

**Comment by alex-cory** [comment]
I really like the `response.json()` idea you put there. That would help solve any of the problems for people wanting to do something like `response.formData()` or any of those other response methods.

**Comment by alex-cory** [comment]
this [PR](https://github.com/alex-cory/use-http/pull/120/files) fixes the `await response.text()` or any other http response type issue.
