### ISSUE TITLE
Provider interceptor uses cached values?

### ISSUE THREAD

**Issue by revolucion** [alex-cory/use-http#135]
I have created a custom Provider with (global) options to send certain headers on all requests via an interceptor. This interceptor should get a value from a context and send it with the headers, but it doesn't seem to update to the new value.

Created a CodeSandbox [here](https://codesandbox.io/s/usefetch-provider-nhjtj)

When you run it and open inspector to check the network calls, you can see that the x-token header remains null on each call, even though the 'token' value is updated in the context as showed in the console and on the component render.

The funny thing is, if I place the exact same interceptor code in the useFetch hook itself, it _does_ send the correct header value.
Like so:

```
	const [request, response] = useFetch({
		interceptors: {
			request: options => {
				console.log("Interceptor called with token", state.token);
				options.headers["x-token"] = state.token;
				return options;
			}
		}
	});
```

**Comment by alex-cory** [comment]
Will take a look asap

**Comment by alex-cory** [comment]
Okay, so we don't typically use onUpdate for something like this. We would do it something like
```js
import React, { useEffect, useState, useContext } from "react";
import { render } from "react-dom";
import { Snowflakes, Center } from "./components";
import { useFetch, Provider } from "use-http";
import { TestContext, TestProvider } from "./context";
import useLocalStorage from 'react-use-localstorage'

import "./styles.css";

const CustomProvider = ({ children }) => {
	const [token, setToken] = useLocalStorage('token')

	const getToken = async () => {
		return 'my-token'
	}

	const options = {
		interceptors: {
			request: async options => {
				if (!token) {
					const newToken = await getToken()
					setToken(newToken)
				}
				console.log("Interceptor called with token", token);
				options.headers["x-token"] = token;
				return options;
			}
		}
	};

	useEffect(() => {
		console.log("Logging token", token);
	}, [token]);

	return (
		<Provider url={window.location.origin} options={options}>
			{children}
		</Provider>
	);
};

const TestFetch = () => {
	const [token] = useLocalStorage('token')

	const [request, response] = useFetch();

	useEffect(() => {
		async function getSomething() {
			console.log("Performing request with token in context as:", token);
			await request.get("/test.json");
			if (response.ok) console.log("Finished.");
		}
		getSomething();
	}, []);

	return (
		<>
			<span>Token is {token}</span>
		</>
	);
};

const App = () => {
	return (
		<TestProvider>
			<CustomProvider>
				<Snowflakes>
					<Center>
						<TestFetch />
					</Center>
				</Snowflakes>
			</CustomProvider>
		</TestProvider>
	);
};
```
Does this help at all?

**Comment by revolucion** [comment]
Thanks for getting back at me!

The onUpdate was something I tried with the idea of "lets see if this works". So that shouldn't have been in the example :)
I understand the example that you're giving, however something still seems to not be working.
I have updated the example with some clearer code perhaps.

You can see in the console how the CustomProvider logs the state object as it should be, however the request is still performed without the updated state values.

[Updated example here]( https://codesandbox.io/s/usefetch-provider-nhjtj for the example.)

**Comment by alex-cory** [comment]
Apologies for the delay on this, but I **think** this [PR](https://github.com/alex-cory/use-http/pull/154) might fix this. Try `v0.2.3`. I'm going to close this. If the issue persists, let me know and I will reopen.
