### ISSUE TITLE
Doesn't work in CodeSandbox

### ISSUE THREAD

**Issue by pkl** [alex-cory/use-http#15]
I can't import/use this as a dependency in a CRA app in codesandbox, any idea why?

**Comment by alex-cory** [comment]
I will check when I get to my computer

**Comment by alex-cory** [comment]
Could you link to the codesandbox? What error is it giving you?

**Comment by pkl** [comment]
Sure: 
https://codesandbox.io/s/j2941z81k5

unpkg looks a little wonky: 
https://unpkg.com/use-http@0.1.58/dist/

**Comment by alex-cory** [comment]
I will take a look at this tonight, but for now, v1.0.50 works

**Comment by alex-cory** [comment]
I will get tests in tonight for this too

**Comment by alex-cory** [comment]
Just kidding, I fixed it now. Try `v1.0.62`
