### ISSUE TITLE
Pagination With Provider Example Not Working

### ISSUE THREAD

**Issue by aditioKLB** [alex-cory/use-http#151]
The pagination with provider example are not working.
New http request is not call after page updates.

**Comment by alex-cory** [comment]
codesandbox link?

**Comment by aditioKLB** [comment]
Sorry I forgot that, the codesandbox link,
https://codesandbox.io/s/usefetch-in-nextjs-xdo88?fontsize=14&hidenavigation=1&theme=dark

**Comment by alex-cory** [comment]
This is my 1st priority today

**Comment by alex-cory** [comment]
This is fixed in [this PR](https://github.com/alex-cory/use-http/pull/153). I was missing some dependencies in the dependencies array. I will let you know once this get's merged and published.

**Comment by alex-cory** [comment]
Okay this is fixed in `v0.2.2`. I updated the documentation with a codesandbox example.

**Comment by alex-cory** [comment]
Also, just a side note. You could write what you had in your sandbox like this
![image](https://user-images.githubusercontent.com/5455859/70002847-24dabc00-1516-11ea-98af-b68c695da76c.png)

**Comment by aditioKLB** [comment]
Okay, thanks you for awesome response
