### ISSUE TITLE
New requests not fired when dependency array changes

### ISSUE THREAD

**Issue by peterssonjesper** [alex-cory/use-http#156]
Hi,

Thanks for the excellent work on this library!

I ran into some issues today, and I'm not sure that this is because of some bug, or simply because I have misunderstood how the API is supposed to work. The case has to do with firing new requests as entries in the dependency array changes.

For instance, I was expecting the following to fire a new request whenever `id` changes:
```javascript
const stuff = useFetch(`/user${id}.json`, [id]);
```

What happens is that the request is initially fired on mount, but as `id` changes, nothing happens.

I've probably misunderstood how this is supposed to work, but if not then this might be some bug that I'm hitting. I have a complete example reproducing it available here: https://codesandbox.io/s/usefetch-dependency-array-slsb9?fontsize=14&hidenavigation=1&theme=dark

Thanks,
Jesper

**Comment by alex-cory** [comment]
What version are you using?

**Comment by alex-cory** [comment]
It's working. Take a look at the network tab, and filter by the word `user`. You can see as I click it makes a call for `user1`, then `user2`, and so on. Here's a screenshot
![image](https://user-images.githubusercontent.com/5455859/70559363-5b7a8d00-1b3b-11ea-9dd4-7f1e3a66f3aa.png)

**Comment by alex-cory** [comment]
Make sure you're using the latest version (currently `0.2.4`), and if something doesn't seem to be quite working in codesandbox, always click the refresh ⟲ button on the package in the dependencies on the left. Sometimes codesandbox can be buggy and load an old version of the npm package. Here's a screenshot for reference.
![image](https://user-images.githubusercontent.com/5455859/70559730-130f9f00-1b3c-11ea-8a27-3568cacd99a1.png)

Going to close this for now, but if the issue persists, just comment again and I'll reopen the issue. 🙂

**Comment by peterssonjesper** [comment]
Omg, you are totally right. I bumped to 0.2.4 (I was on 0.2.1 locally, not sure about what version codesandbox was using) and now it works like a charm!

Big thanks for the quick response!

Cheers
