### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by hug0b** [alex-cory/use-http#162]
Hello I have an issue when using the `useFetch` hook to fire an http call.
After calling the hook on mount, the data prop is empty and I get the following in the error prop: `TypeError: "NetworkError when attempting to fetch resource.`

In the browser console the network call succeeded with code 200 and returns a valid JSON response.

Am I missing something the error doesn't tell me ? Or could it be a bug ?

**Comment by alex-cory** [comment]
Codesandbox please

**Comment by hug0b** [comment]
Turns out it was a CORS error... oops 😅

**Comment by alex-cory** [comment]
No worries! Sounded kind of like that might be the case
