### ISSUE TITLE
onUpdate doesn't work

### ISSUE THREAD

**Issue by sabba88** [alex-cory/use-http#167]
Hi,
I try the pagination example in my App but the fetch is done one time only on onMount. When I update page state nothing is done. Checking the Network tab in Google Chrome DevTools any other request is done.
This is my code

```
export default function Reservation() {
  const [page, setPage] = useState(1);

  const { loading, error, data: reservations } = useFetch(
    {
      path: `${endpointShuttles}?page=${page}`,
      onNewData: (currReservations, newReservations) => [...currReservations, ...newReservations.data],
      data: [],
    },
    [page],
  ); // onMount AND onUpdate whenever `page` changes

  // Used to test if useEffect is fired
  useEffect(() => console.log('useEffect page', page), [page]);

  return (
    <>
      <h1>Pagination</h1>
      {error && 'Error!'}

      <ul>{reservations && reservations.map((user, i) => <li key={i}>{user.shuttleCode}</li>)}</ul>
      <button type="submit" onClick={() => setPage(page + 1)}>
        {loading ? 'Loading...' : 'Load Data'}
      </button>
    </>
  );
}
```

The server return 200 with the correct data.
The useEffect added to test if page change is fired and console.log woks fine.
In upper component I use Provider with some options and custom interceptors but in the request interceptor the console.log is fired only at onMount.

It seems that the change of page state is not triggered.

Someone have any idea?

Thanks in advance,
Samuele

**Comment by alex-cory** [comment]
Please make a codesandbox. [Here is a template](https://codesandbox.io/s/usefetch-provider-pagination-exttg)

**Comment by sabba88** [comment]
Hi Alex,
thanks for your reply. Putting the code in codesandbox everything works fine.  After some test the problem was just the version of the library. I have installed the 0.2.1 version, I upgrade to 0.2.5 and everything is ok.
In the realeases note this function is added in the version 0.2.1 maybe there was some issue that was solved in newer versions.

Samuele
