### ISSUE TITLE
Weird types

### ISSUE THREAD

**Issue by anilanar** [alex-cory/use-http#172]
**Describe the bug**
```
export interface ReqBase<TData> {
    data: TData | undefined;
    loading: boolean;
    error: Error;
}
```

That should be replaced with 

```
type ReqBase<TData> = 
  | {
    data: undefined.
    error: undefined,
    loading: false,
  }
  | {
    data: TData,
    error: undefined,
    loading: true,
  }
  | {
    data: undefined,
    error: Error,
    loading: true,
  };
```

**Comment by alex-cory** [comment]
Submit a PR! Also, I'm a little confused here.
`data` can be undefined when `loading` is true
`data` can be defined when `loading` is false
`error` can be defined when `loading` is false

**Comment by alex-cory** [comment]
Closing this for now. If you want to clarify things more or suggest changes, let me know. I can re-open the issue.
