### ISSUE TITLE
response.ok undefined when response is served from cache

### ISSUE THREAD

**Issue by TheDuc** [alex-cory/use-http#180]
**Describe the bug**
response.ok is undefined on a first call, when the response is cached

take the Basic Usage example (snippet):
```
  const [todos, setTodos] = useState([])

  const [request, response] = useFetch('https://example.com')
  
  async function initializeTodos() {
    const initialTodos = await request.get('/todos')
    if (response.ok) setTodos(initialTodos)    // <------ problem here on first request
  }
```

response.current is never set when the data was served from cache, so response.ok is undefined

**Expected behavior**
Either set response.current.ok true, ór update basic usage example

**Comment by alex-cory** [comment]
Thank you for the bug report! I will get to this as soon as possible! A workaround while you're waiting for this patch is `cachePolicy: 'no-cache'`.  I know how to fix this.

**Comment by TheDuc** [comment]
thanks for the quick response!
I already implemented the workaround, but would be nice to have caching as well

**Comment by alex-cory** [comment]
I have a branch with this fix. Lots of stuff going on so bare with me!

**Comment by alex-cory** [comment]
@TheDuc can you confirm this works? `v0.3.2`?

**Comment by alex-cory** [comment]
Going to close this. If the issue persists, just comment back here letting me know and I'll reopen.

**Comment by pdrvsky** [comment]
Yes, problem persists on my side also (version 0.3.4).

**Comment by alex-cory** [comment]
Okay, I found the problem. Premature optimizations. See it working [here](https://codesandbox.io/s/usefetch-different-response-types-c6csw). This should work in `v0.3.6`
