### ISSUE TITLE
Incorrect argument parsing without options

### ISSUE THREAD

**Issue by Gerhut** [alex-cory/use-http#185]
**Describe the bug**
`get` function changes every time when calling in `useFetch(url, deps)` format.

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/compassionate-carson-66sbu

**Expected behavior**
Keep optionsNoURLs undefined if second parameter is array in https://github.com/alex-cory/use-http/blob/master/src/useFetchArgs.ts#L72

**Comment by alex-cory** [comment]
On vacation until March 3, but will take a look asap.

**Comment by alex-cory** [comment]
Feel free to submit a PR! ❤️

**Comment by alex-cory** [comment]
This is my next thing I'm gonna work on.  @maxquinn You interested in taking a look at this one? I'm either going to work on this or Suspense support tomorrow.

**Comment by maxquinn** [comment]
Yeah sure. I'll take a look in the morning

**Comment by alex-cory** [comment]
@maxquinn if this starts getting too far down a rabbit hole, let me know. Happy to help. We potentially might need to split `loading` state out of `request` object.

**Comment by alex-cory** [comment]
This is implemented in `v0.4.1`. Closing this issue. Let me know if the issue persists, and I'll re-open the issue.

**Comment by Gerhut** [comment]
Hi, it seems this is fixed after 2 major versions (I am reported in 0.2.9). Do we have some change logs or migration guides about these major version updates?

**Comment by alex-cory** [comment]
I am about to post a major release very soon. In that I will post all the updates, new features, etc! Bare with me.

**Comment by alex-cory** [comment]
@Gerhut Here's the [new release](https://github.com/ava/use-http/releases/tag/1.0.2)! If you are having issues migrating to the new version, let me know your troubles and I will help as much as possible!
