### ISSUE TITLE
baseUrl does not work when passing Options & RequestInit as arg1 to useFetch

### ISSUE THREAD

**Issue by audiolion** [alex-cory/use-http#19]
e.g.

```ts
useFetch({
  baseUrl: 'https://api.example.com',
  url: '/posts',
});
```

won't use the `baseUrl`. I ran into this creating a small wrapper around `useFetch` to always place the `baseUrl` in there. I have a workaround but wanted to bring up the issue I ran into.

**Comment by alex-cory** [comment]
ah, yeah that's not exactly how it works. You can only choose `baseUrl` or `url` currently. If `axios` supports this feature, I will implement, otherwise only use `baseUrl` if you're using relative routes and `url` for pretty much everything else. Also, if I'm misunderstanding what you're asking let me know.

**Comment by alex-cory** [comment]
I think what you're looking for is:
```js
const request = useFetch({
  baseUrl: 'https://api.example.com'
})

request.post('/posts', { your: 'post body' })
```
Am I correct in this assumption?

**Comment by audiolion** [comment]
yeah, basically. I was trying to something like:

```js
const baseUrl = process.env.REACT_APP_API_URL;

const myUseFetch = (relativeUrl) => {
  const request = useFetch({
    baseUrl,
    relativeUrl,
  });
};
```

Ended up doing:
```js
const baseUrl = process.env.REACT_APP_API_URL;

const myUseFetch = (relativeUrl) => {
  const request = useFetch({
    url: `${baseUrl}${relativeUrl},
  });
};
```

Thanks for the lib!

**Comment by alex-cory** [comment]
ahhh! I see what you're saying now. Yep, that is probably the best way to do that for now. Eventually there will be a provider that you can use and you can set a baseUrl in that, but haven't implemented that fully yet. 😊
