### ISSUE TITLE
Response on unmounted component

### ISSUE THREAD

**Issue by herisn23** [alex-cory/use-http#198]
Its possible to add support to handle unmounted component?

For example:
Any component call long running task but that component is unmounted for some reasons while request is still processing.
This use case cause error in react, because useFetch returns response on unmounted component.

**Comment by herisn23** [comment]
Sorry, my mistake. It works. But no when unmounting component on top level interceptor. (Server returns 401 and i must show login page instead of rest of application)

**Comment by alex-cory** [comment]
Hm... can you elaborate some more? A codesandbox would help a lot.
