### ISSUE TITLE
Next JS Support ? 

### ISSUE THREAD

**Issue by Ishtiaque-Shaad** [alex-cory/use-http#20]
Hello there... Does it support next.js? If so, then will you please provide an example?

**Comment by alex-cory** [comment]
yep! I will 100% do that tonight. Before publishing I usually test in next.js app so.

**Comment by alex-cory** [comment]
Okay, I added it to the README, but here's the [codesandbox link](https://codesandbox.io/s/usefetch-in-nextjs-nn9fm)!
![](https://media1.giphy.com/media/11sBLVxNs7v6WA/giphy.gif)

**Comment by Ishtiaque-Shaad** [comment]
Though, yesterday I have already done the same procedure in NextJS for fetching data & it is working, but thanks for the update... 

Cheers ... Hooray

**Comment by alex-cory** [comment]
Yes, there is an active todo out for this at the bottom of the README 😊 I just haven't gotten to it yet.

**Comment by oknoorap** [comment]
Hey, it's still not working
