### ISSUE TITLE
Unclear how I should clear the cache when a user logs out

### ISSUE THREAD

**Issue by benarmston** [alex-cory/use-http#206]
When a user logs out, I wish to clear any cached data for them.  It is not clear how I would do this.

**Comment by alex-cory** [comment]
I need to add this. The way I was planning on doing this was
```js
const { cache } = useFetch()

cache.clear()
```
But it needs to be implemented. Bare with me, I'll add it in asap. Hopefully by today/tomorrow

**Comment by alex-cory** [comment]
This feature has been added to `v0.3.9`
