### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by w10036w** [alex-cory/use-http#21]
It is really helpful if it can support react native as well.

But as of now it will not get any response, without throwing any errors or going to `finally {}` logic: 

```js
// useFetch.js (after transpile, in debugger)
// line 76
// logic ends here and no further
const response = yield fetch(url + query, Object.assign({ method }, options, { headers: Object.assign({ 'Content-Type': 'application/json' }, options.headers) }));
```
My component code is [here](https://codesandbox.io/s/6l8231y8mw) and it works well in web.
This seems like a fetch issue for React Native, any ideas?

**Comment by alex-cory** [comment]
Looking into it now :)

**Comment by alex-cory** [comment]
Ok, I'm exhausted. I got it mostly working, but will send you the link to the working codesandbox in the morning when I wake up. 😊

**Comment by alex-cory** [comment]
I'm going to add this as an example in the README too! 😛Thanks for pointing this out!

**Comment by alex-cory** [comment]
By the way, as far as your error goes, I'm gonna make a guess and say it was that you ran out of your daily request limit for https://jsonplaceholder.typicode.com/posts.

**Comment by w10036w** [comment]
Not really as I test right now cuz web (localhost) always works.

**Comment by alex-cory** [comment]
are you free to hop on a videochat and screenshare? I'm not able to reproduce this bug

**Comment by alex-cory** [comment]
I guess I'm just confused where it's erroring because when I run your codesandbox, it's doing exactly what it's supposed to.
![image](https://user-images.githubusercontent.com/5455859/58297294-1869ef80-7d8c-11e9-910b-10fb2726f1df.png)
It does not fetch the `newTodo`, but it fetches the `todos`.

**Comment by w10036w** [comment]
> the sandbox is still in web; I paste the code for you to copy and run in react-native

my codebase
https://github.com/w10036w/cross-platform-react-starter/tree/apollo/master
`npm run ios`

The key file (same to my sandbox): src/components/_example/example.jsx

<img width="962" alt="screenshot" src="https://user-images.githubusercontent.com/3350260/58297285-cbc4f980-7e09-11e9-9c0d-f3854615d741.png">

**Comment by alex-cory** [comment]
ok looking into it now

**Comment by alex-cory** [comment]
XCode is taking forever to download... bare with me.

**Comment by alex-cory** [comment]
Just want you to know, you have not been forgotten! As a part of this I've been trying to get tests up and running. Please bare with me. 🙏

**Comment by alex-cory** [comment]
Sorry for taking a million years to fix this one. I'm still checking into this. I recently found a way to test react-native stuff for this in [this post](https://stackoverflow.com/questions/45842088/react-native-mocking-formdata-in-unit-tests).

**Comment by alex-cory** [comment]
Sorry for taking so long to get this done, but react native is officially supported in `v0.1.87`
