### ISSUE TITLE
Can't perform basic request with v4.1

### ISSUE THREAD

**Issue by nth-chile** [alex-cory/use-http#216]
**Describe the bug**
It looks like requests are not being sent because of the last update (v4.1)

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/wispy-wind-p7ve5

**To Reproduce**
1. Go to https://codesandbox.io/s/wispy-wind-p7ve5
2. Open console, see the correct response
3. Switch the use-http dependency version from 4.0 to 4.1

**Comment by alex-cory** [comment]
On it

**Comment by alex-cory** [comment]
This should be fixed in `v0.4.3`. If the issue persists, let me know and I'll re-open the issue.
