### ISSUE TITLE
Refetch data

### ISSUE THREAD

**Issue by JanSmolko** [alex-cory/use-http#217]
I have similar question as in #161 and that is: 
**How can I refetch data?**  (when I dont want to change anything in URL). 

I thought that I can use it this way: 
```
const { get, data, loading, error } = useFetch(
    path,
    {
      cache: 'no-cache'
    },
    []
  )
```
and then in some callback use 
```
get()
```

but I can call new request only with something like
```
get("?"+timestamp)
```

Is there any way to do it without changing URL? Or am I missing something?

**Comment by alex-cory** [comment]
```js
const { get, data, loading, error } = useFetch(url, {
  path: '/you/path/here',
  cache: 'no-cache'
}, [])
```

**Comment by alex-cory** [comment]
Going to close this, but feel free to comment more if you have any more questions or need more clarifications!

**Comment by JanSmolko** [comment]
Sorry but I still dont get it. (To me) it seems like you answered to some other issue :/

**Comment by alex-cory** [comment]
Could you make a codesandbox showing me the problem please? :)

**Comment by alex-cory** [comment]
Oh, maybe try `cachePolicy: 'no-cache'`

**Comment by JanSmolko** [comment]
> Oh, try `cachePolicy: 'no-cache'`. If you don't want cache anywhere, you can set it in the `Provider`

https://codesandbox.io/s/stoic-meadow-yu6g9

OMG, thank you. thats it. 

BTW: typescript had no problem with `cache: 'no-cache'` and what is really working is `cachePolicy: CachePolicies.NO_CACHE`

**Comment by tuvudu** [comment]
@alex-cory Many Thanks!
