### ISSUE TITLE
SSR Not working

### ISSUE THREAD

**Issue by oknoorap** [alex-cory/use-http#32]
I'm using version `0.1.68` but nothing is working. This is my codes:

```tsx
import React from "react";
import useFetch from "use-http";

export default () => {
  const stories = useFetch(
    "https://hacker-news.firebaseio.com/v0/topstories.json",
    {
      onMount: true
    }
  );

  if (stories.error) return "Error";
  if (stories.loading) return "Loading";

  return <pre>{JSON.stringify(stories.data, null, 2)}</pre>;
};

```

**Comment by alex-cory** [comment]
What is the error?

**Comment by oknoorap** [comment]
Please check nextjs example on the codesandbox, it also doesn't works

**Comment by alex-cory** [comment]
Everything should be working. Please use `v0.1.73`.  See [codesandbox](https://codesandbox.io/s/usefetch-in-nextjs-nn9fm)

**Comment by khusamov** [comment]
@alex-cory Your example is not similar to the example of the author of the question. You have a file download by clicking. That is, client-side rendering. And server-side rendering is required.

**Comment by khusamov** [comment]
This example differs from the example presented on the use-http website


```
export default () => {
  const stories = useFetch("https://hacker-news.firebaseio.com/v0/topstories.json");
  if (stories.error) return "Error";
  if (stories.loading) return "Loading";
  return <pre>{JSON.stringify(stories.data, null, 2)}</pre>;
};
```

In theory, a request to the hacker-news site should occur on the server. But I checked - this does not happen. The request is sent alas on the client.
