### ISSUE TITLE
useGet not working from 0.1.66 version

### ISSUE THREAD

**Issue by mczeplowski** [alex-cory/use-http#35]
Last working version is 0.1.65. Situation looks like url has not been passed to request function, because request goes to current location(localhost).

Example of use: 
`const [users, usersLoading] = useGet('https://api.example.com/v2/users', { onMount: true })`

**Comment by alex-cory** [comment]
Will get to this asap

**Comment by alex-cory** [comment]
Everything should be working. Please use `v0.1.73`.  See [codesandbox](https://codesandbox.io/s/usefetch-in-nextjs-nn9fm)
