### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alex-cory** [alex-cory/use-http#36]
![image](https://user-images.githubusercontent.com/5455859/60610875-c39d9980-9d79-11e9-911f-28874002f550.png)
![image](https://user-images.githubusercontent.com/5455859/60610881-c5fff380-9d79-11e9-9c1f-44d9d17e31f6.png)
![image](https://user-images.githubusercontent.com/5455859/60610883-c7c9b700-9d79-11e9-91b5-e51717371dd8.png)

**Comment by alex-cory** [comment]
@dagda1 which logo do we like?

**Comment by dagda1** [comment]
you decide man.  I'm happy whatever

**Comment by alex-cory** [comment]
I can still change it lol what do you like best?
