### ISSUE TITLE
Additional Response Data

### ISSUE THREAD

**Issue by NTARelix** [alex-cory/use-http#55]
### Scenario
I'm creating a simple CRUD app with authentication. My API uses HTTP status codes and response headers to indicate certain information. Some status code examples:
* Check if user is logged in when they aren't: `GET /auth` => `403`
* Login with invalid credentials: `POST /auth` => `403`

### Problem
Using `use-http` to make HTTP requests, I'm unable to determine the HTTP status or response headers of my requests, forcing me to modify my API to include these values in the response body (not so easy when consuming a third party API).

### Proposal
Within the `useFetch` output, include some of the values from `fetch`'s `Response`.
Some ideas:
- Just pass back fetch's response object directly: `const [myData, isLoading, error, request, response] = useFetch<IMyDataType>('/api/path')`
- Extract values from the response and pass them back individually: `const { responseStatusText, responseHeaders, responseOk } = useFetch<IMyDataType>('/api/path')`
- Extract values from the response and pass them back in a custom response object: `const { useHttpResponse } = useFetch<IMyDataType>('/api/path')`

Is there a solution I'm missing? Or does anyone have any thoughts?

**Comment by alex-cory** [comment]
I like this. I might do something like
```js
const request = useFetch('https://example.com')

async function addTodo() {
  // instead of this
  const todos = await request.get('/todos')
  // maybe this
  const { data: todos, headers, ok, ...etc } = await request.post('/todos', {
    title: 'cool',
  })
}
```
also this might be something to think about, but idk how I feel about it
```js
const { request, response: { data, ok, headers } } = useFetch('https://example.com')

async function addTodo() {
  await request.post('/todos', {
    title: 'cool',
  })
}
```

**Comment by alex-cory** [comment]
It's basically
```js
const request = useFetch('https://example.com')

async function addTodo() {
=
  const response = await request.post('/todos', {
    title: 'cool',
  })
  if (response.ok) setTodos([...todos, response.data])
}
```

**Comment by alex-cory** [comment]
Man, the more that I think about it, I feel like it would be cool if the syntax was like
```js
const [request, response] = useFetch('url.com')
const [{ loading, error }, { data, ok }] = useFetch('url.com')
```

**Comment by alex-cory** [comment]
@NTARelix btw, I'm building this right now 
![](https://media2.giphy.com/media/7eAvzJ0SBBzHy/giphy.gif)

**Comment by NTARelix** [comment]
Awesome! I've been thinking about implementing it myself and opening a PR, but I haven't had time to do much being clone and glance at the repo. I'll be happy to take a look when you've got something.

**Comment by alex-cory** [comment]
I have something. Checkout [this branch](https://github.com/alex-cory/use-http/compare/new-array-destructure-syntax-and-tests#diff-326372ad77dca3e7c2460c8d26329f41R37-R146). I'm changing the api to be
```jsx
const [request, response, loading, error] = useFetch()
```
and you can always do
```jsx
const { request, response, loading, error, get } = useFetch()
```

**Comment by alex-cory** [comment]
Feel free to pull the branch if you want. I'm just debugging why I'm getting an infinite loop in some of the tests. It might be because of the dependencies in the `useEffects` in `useFetch`

**Comment by jpennal** [comment]
+1 - Looking forward to this feature.

**Comment by alex-cory** [comment]
The tests are so annoying, otherwise this feature would already be in...

**Comment by alex-cory** [comment]
@Markus-ipse this feature for the `onMount` loading === true by default is implemented [in this branch](https://github.com/alex-cory/use-http/tree/lots-of-fixes-and-features) and all the tests are working. Will merge today

**Comment by alex-cory** [comment]
It has been tested and published. Woooo!
![](https://media1.giphy.com/media/gLoLF3wgCadMXgjXIi/giphy.gif)
