### ISSUE TITLE
Trigger new request on url change

### ISSUE THREAD

**Issue by Markus-ipse** [alex-cory/use-http#70]
Currently I can't figure out a short and simple way to fetch data onMount and when the url changes.

The code below only triggers on mount, and looking at the docs (and source code) it doesn't seem like useGet takes a dependency array (like useEffect does) that indicates when the effect should execute again, is there some other option to get it re-run on url change as well as mount? Am I missing some other trivial way of accomplishing this?

```
import {useGet} from 'use-http'

function Todos(props) {
  const options = {
    onMount: true // will fire on componentDidMount
  }

  const todos = useFetch('https://example.com/todos/' + props.someID, options)

  return (
    <>
      {request.error && 'Error!'}
      {request.loading && 'Loading...'}
      {(todos.data || []).length > 0 && todos.data.map(todo => (
        <div key={todo.id}>{todo.title}</div>
      )}
    </>
  )
}
```

**Comment by alex-cory** [comment]
So I think eventually I'm going to be deprecating the `onMount` feature. The best way to accomplish this is
```js
import useFetch from 'use-http'

function Todos({ someID }) {
  const { get, data, loading, error } = useFetch('https://example.com/todos')
  const { location } = useRouter()

  useEffect(() => { // this should fire onMount and when someID changes
    get(`/${someID}`
  }, [someID, get])

  return (
    <>
      {error && 'Error!'}
      {loading && 'Loading...'}
      {(data || []).length > 0 && data.map(todo => (
        <div key={todo.id}>{todo.title}</div>
      )}
    </>
  )
}
```
Alternatively this might work if `someID` isn't coming from a url change
```js
import useFetch from 'use-http'
import useRouter from 'use-react-router'

function Todos({ someID }) {
  const { get, data, loading, error } = useFetch('https://example.com/todos')
  const { location } = useRouter()

  useEffect(() => { // this should fire onMount and when someID changes
    get(`/${someID}`)
  }, [location.pathname, get])

  return (
    <>
      {error && 'Error!'}
      {loading && 'Loading...'}
      {(data || []).length > 0 && data.map(todo => (
        <div key={todo.id}>{todo.title}</div>
      )}
    </>
  )
}
```

**Comment by Markus-ipse** [comment]
Your first example is the way I'm currently solving it now, but it feels a bit superfluous to me to have to use a `useEffect` to call a function I got from my fetch-hook, when all I want is for it to fetch anytime the url changes.

It's also a minor annoyance that the `loading` flag will be false before it turns `true`, which means I cannot just do an early return with a `<Spinner />` if `loading === true`, but it's probably not a good practice on my end to assume all data exists just because ´loading === false` 😅 

Do you have any thoughts on future changes to simplify this particular kind of flow or is it perhaps something you've already considered and found some downsides to that makes it not worth it (and if not, are you accepting PRs 😄)? 

Thanks!

**Comment by alex-cory** [comment]
I am accepting PRs! :) What did you have in mind for this?

I've also been thinking about the `loading` state. Are there any cases you can think of where having `loading === true` as the default where it might be a bad thing? If not, I'm happy to make it `true` by default and once the fetch is called, set it to false

**Comment by alex-cory** [comment]
Before you get too far on a PR though, let's discuss some possible solutions :)

**Comment by Markus-ipse** [comment]
I can't really think of a case where setting `loading === true` as the default would be problematic ( provided that request will happen onMount), that's how I've always had it when doing my fetching manually.

I haven't spent a lot of time thinking about it yet, but perhaps adding the option to pass in a dependency array, like `useEffect` and adding another option (or changing `onMount`) that will re-trigger the request anytime something in the dependency array changes?

```javascript
import {useGet} from 'use-http'

function Todos(props) {
  const options = {
    onMount: true 
  }

  const todos = useFetch('https://example.com/todos/' + props.someID, options, [props.someId, options]) // 1

  // 2
  if (todos.loading) { return <MySpinner /> }
  
  if (todos.error) { return <h2>Oopsie</h2> }

  return (
    <>
      {(todos.data.map(todo => ( // 3
        <div key={todo.id}>{todo.title}</div>
      )}
    </>
  )
}
```
1 -> I'm not sure if the dependency array makes sense when `onMount == false` but my guess is that it wouldn't hurt.

2 -> if `loading` defaults to `true`  I can just do an early return with a loading indicator and not have to think about handling the existence or non-existence  of the response data yet.

3 -> `(todos.data || []).length > 0 && todos.data.map(...)` can be reduced to just `todos.data.map(...)` provided that I trust that my backend will always deliver an array.

But the last two are mostly selling points for me only because I'm doing a lot of prototyping at the moment..

**Comment by Markus-ipse** [comment]
If I uncomment the content of the dependency array for [`makeFetch`](https://github.com/alex-cory/use-http/blob/master/src/useFetch.ts#L75) and  for the [`useEffect`](https://github.com/alex-cory/use-http/blob/master/src/useFetch.ts#L127) that handles the `onMount` logic, and then add `url` as a dependecy arg for [`get`](https://github.com/alex-cory/use-http/blob/master/src/useFetch.ts#L79), i.e. `const get = useCallback(makeFetch(HTTPMethod.GET), [url])`, then I get the desired behaviour for GET-requests, anytime the url changes another request is triggered.

Is there a specific reason for the dependency arrays being commented out for  [`makeFetch`](https://github.com/alex-cory/use-http/blob/master/src/useFetch.ts#L75) and  [`useEffect`](https://github.com/alex-cory/use-http/blob/master/src/useFetch.ts#L127)?

**Comment by alex-cory** [comment]
They were causing an infinite loop in some of the tests. I just haven't had time to come back and fix everything. Feel free to make a PR. :) Just make sure all the tests are working please!

**Comment by alex-cory** [comment]
> I can't really think of a case where setting `loading === true` as the default would be problematic ( provided that request will happen onMount), that's how I've always had it when doing my fetching manually.
> 
> I haven't spent a lot of time thinking about it yet, but perhaps adding the option to pass in a dependency array, like `useEffect` and adding another option (or changing `onMount`) that will re-trigger the request anytime something in the dependency array changes?
> 
> ```js
> import {useGet} from 'use-http'
> 
> function Todos(props) {
>   const options = {
>     onMount: true 
>   }
> 
>   const todos = useGet('https://example.com/todos/' + props.someID, options, [props.someId, options]) // 1
> 
>   // 2
>   if (todos.loading) { return <MySpinner /> }
>   
>   if (todos.error) { return <h2>Oopsie</h2> }
> 
>   return (
>     <>
>       {(todos.data.map(todo => ( // 3
>         <div key={todo.id}>{todo.title}</div>
>       )}
>     </>
>   )
> }
> ```
> 
> 1 -> I'm not sure if the dependency array makes sense when `onMount == false` but my guess is that it wouldn't hurt.
> 
> 2 -> if `loading` defaults to `true` I can just do an early return with a loading indicator and not have to think about handling the existence or non-existence of the response data yet.
> 
> 3 -> `(todos.data || []).length > 0 && todos.data.map(...)` can be reduced to just `todos.data.map(...)` provided that I trust that my backend will always deliver an array.
> 
> But the last two are mostly selling points for me only because I'm doing a lot of prototyping at the moment..

For this, I think there are times that you don't want `loading` to be set to true by default. If you want to submit a form, you don't want loading `true` by default, only when you click submit. But, if this is the desired thing, then we could add something like:
```js
<Provider url='' options={{ initialLoading: true }}><App /></Provider>
```

**Comment by Markus-ipse** [comment]
> For this, I think there are times that you don't want `loading` to be set to true by default. If you want to submit a form, you don't want loading `true` by default, only when you click submit. But, if this is the desired thing, then we could add something like:
> 
> ```js
> <Provider url='' options={{ initialLoading: true }}><App /></Provider>
> ```

Isn't it enough to check if `onMount === true` and/or it's a GET request?

**Comment by alex-cory** [comment]
I was literally just about to post that lol. I think that would work pretty well

**Comment by alex-cory** [comment]
I'm so busy currently and want to add this in, but just strapped for time. I really want this. Feel free to submit a PR ❤️
![](https://media3.giphy.com/media/3HEJHWu8loqmMyng64/giphy.gif)

**Comment by alex-cory** [comment]
I'm down to pair with you on it :)

**Comment by Markus-ipse** [comment]
I started looking into it a few weeks ago, but I got stuck on the infinite loop in the tests, so I rage-quit after two days. Then I started looking into it again yesterday and tried just inputing the URL and nothing else to the various dependency arrays and I no longer get the infinite loop, but I get 3 failed tests, but I've unable to setup VS Code to debug Jest tests written typescript so I'm a bit stuck again :'(

**Comment by alex-cory** [comment]
Hop on spectrum and we can chat. https://spectrum.chat/use-http?tab=posts

**Comment by alex-cory** [comment]
I should be able to hop back on this, this week.

**Comment by alex-cory** [comment]
Also, I think the community seems to want `onMount` so maybe I'll leave it for now. I like the `loading === true` by default when `onMount` is true. That makes sense. For your question about trigger new request on url change, I was also thinking about something like:
```jsx
const App = () => {
  const { location } = useReactRouter()
  const request = useFetch('url', {
    onUpdate: [location.pathname]
  })
}
```

**Comment by Markus-ipse** [comment]
For my particular case it's about triggering a new request when the url parameter changes, not the page you're on. More concretely, say I have a page where i show the details for a product and there is a dropdown where I can select a different product. 

```
const App = () => {
  const [selectedProductId, setSelectedProductId] = useState();
  const request = useFetch('someurl/product/' + selectedProductId)
 // ...etc.
}
```

But maybe that was your point as well and I just misunderstood?

**Comment by alex-cory** [comment]
```jsx
import {
  useQueryParams,
  StringParam,
  NumberParam,
  ArrayParam,
} from 'use-query-params';

const App = () => {
    // something like: ?x=123&q=foo&filters=a&filters=b&filters=c in the URL
  const [query] = useQueryParams({
    x: NumberParam,
    q: StringParam,
    filters: ArrayParam,
  });
  const request = useFetch('url', {
    onUpdate: [query.x, query.q, query.filters]
  })
}
```

**Comment by Markus-ipse** [comment]
Right, I see.. Btw, why not use the standard dependecy-array-as-last-argument syntax that all(?) base react hooks follow?

```
const App = () => {
  // when productID changes, rerun the fetch
  //  for route: https://url.com/product/:productID
  const { match: { params } } = useReactRouter()
  const request = useFetch(`https://url.com/product/${params.productID}`, [params.productID])
}
```

The only downside I can see is having to accept between 1 and 3 argument and then using typeof checks to figure out if it was called with:
```
useFetch(url, options, deps)
useFetch(url, options)
useFetch(url, deps)
usefetch(url)
```

**Comment by alex-cory** [comment]
I'm not 100% opposed, it just adds a lot of complexity behind the scenes because of all the type checking

**Comment by alex-cory** [comment]
@Markus-ipse this feature for the `onMount` loading === true by default is implemented [in this branch](https://github.com/alex-cory/use-http/tree/lots-of-fixes-and-features) and all the tests are working. Will merge today

**Comment by Markus-ipse** [comment]
@alex-cory it's not that confusing, and confusion and be solved by documentation, so considering the complexity you mentioned it's probably a worthy trade-off.

**Comment by alex-cory** [comment]
Okay, I added `onUpdate`. It's possible in the future we change this to a better name, but for now this works and should do exactly what you're looking for. 😊Going to close this. Feel free to reopen if something doesn't work or if you have some more syntax ideas!

**Comment by alex-cory** [comment]
@Markus-ipse so it looks like the overwhelming majority of people like your suggestion for the dependency array as a final argument to trigger it. I will be implementing this soon ^_^

**Comment by alex-cory** [comment]
I do have a question for you though on syntax for pagination. With this new dependency array, what would you name the `pagination` part? Maybe `onNewData` or maybe the `data` field (which set's the default) could accept a callback function?
```js
const App = () => {
  const [page, setPage] = useState(1)
  const { data, loading } = useFetch({
    onMount: true,
    path: `/todos?page=${page}&pageSize=15`,
    paginate: (currData, newData) => [...currData, ...neweData],
    data: []
  }, [page])
  
  return (
    <>
      {data.map(item => <div key={item.id}>{item.name}</div>}
      {loading ? 'Loading...' : <button onClick={() => setPage(page + 1)}>Load More</button>}
    </>
  )
}
```

**Comment by alex-cory** [comment]
https://github.com/alex-cory/use-http/pull/145

**Comment by Markus-ipse** [comment]
Sorry, I've been quite swamped at work so I haven't had the time to look at the example you posted and really think about it, but I looked at the PR now and I'd just like to say that I agree with your final decision :)
