### ISSUE TITLE
About this code：Object.prototype.toString.call(obj)

### ISSUE THREAD

**Issue by nanyang24** [alex-cory/use-http#9]
I have a question about this line of code

https://github.com/alex-cory/use-http/blob/7715b206a1790ad2d44e311e1e3fb13a5dfc02b4/src/useFetch.js#L4

Why not write it like this：

```js
 const isObject = obj => Object.prototype.toString.call(obj) === '[object Object]' 
```
I think you must have a special consideration, so Im very curious.
Could you tell me what your thought if you have time.
THX~

**Comment by alex-cory** [comment]
Actually that's just a typo LOL nice catch :)

**Comment by alex-cory** [comment]
Do you wanna do a PR? :) Otherwise I can do it

**Comment by nanyang24** [comment]
@alex-cory 
😃 No problem~
I'll create a PR this afternoon（🇨🇳time zone）
