### ISSUE TITLE
doesn't support ie11

### ISSUE THREAD

**Issue by fred8617** [alex-cory/use-http#93]
![image](https://user-images.githubusercontent.com/35049517/65581276-c04b3000-dfad-11e9-9517-c107b8d7a28a.png)

**Comment by Fled8617** [comment]
i need to add these polyfills
import 'promise-polyfill/src/polyfill';
import 'unfetch/polyfill';
import 'abortcontroller-polyfill'
import 'url-search-params-polyfill';

**Comment by alex-cory** [comment]
Will hop to this soon

**Comment by alex-cory** [comment]
@Fled8617 It sounds like you might be on a Microsoft computer since you're using IE. It's kind of a pain to test IE on mac. Would greatly appreciate if you could submit a PR!

**Comment by alex-cory** [comment]
I'm so excited I'm pretty sure I figured out a way to make this work.

**Comment by alex-cory** [comment]
This might be fixed as of https://github.com/alex-cory/use-http/pull/196
As soon as I get a windows machine I'll test this, but anyone who has a windows machine who might be able to confirm that this works, please comment on here so I can close this.

**Comment by Akswii** [comment]
It's not working for ie11 without the polyfills mentioned by @fred8617

**Comment by alex-cory** [comment]
Mind submitting a PR @Akswii? I removed the `Proxy` so it shouldn't be too far off.

**Comment by Akswii** [comment]
Sorry, I don't have the time to look into it. Included the polyfills and got it working for my project. I appreciate your work @alex-cory 🙏

**Comment by alex-cory** [comment]
@Akswii so you didn't need to add a polyfill for [`Object.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)?

**Comment by Akswii** [comment]
![image](https://user-images.githubusercontent.com/9350120/76288789-dc1a6800-62a7-11ea-98c5-d41a11b40874.png)
These are my current polyfills. I think a polyfill for `Object.entries` is included in one of the CRA polyfills.

**Comment by Akswii** [comment]
![image](https://user-images.githubusercontent.com/9350120/76396754-13f1e000-637a-11ea-9743-ab156d389739.png)
I double checked, Object.entries is not polyfilled with the `react-app-polyfill`, nor in any of the other packages as far as I can tell. Not sure if this is helpful or not @alex-cory

**Comment by alex-cory** [comment]
@Akswii I'll make a branch, but could you pull down the branch and test it on your windows machine? Steps
```sh
git clone git@github.com:alex-cory/use-http.git
cd ./use-http
git checkout ie-support
yarn
yarn link
cd ..
create-react-app use-http-cra-app
cd ./use-http-cra-app
yarn
yarn link use-http
cd ../use-http
npm link ../use-http-cra-app/node_modules/react
npm link ../use-http-cra-app/node_modules/react-dom
cd ../use-http-cra-app
yarn start
```
Now just go into your `use-http-cra-app/src/App.js` and import `use-http` and test it in ie.

**Comment by Akswii** [comment]
I had to do `yarn build` in `use-http` to make the test project work.

After adding the basic cra-app polyfill it seems like your ie-support fix branch is working. No need for me to polyfill anything extra. Nice! 🔥

**Comment by alex-cory** [comment]
I'm so excited

**Comment by alex-cory** [comment]
@Akswii when you say the basic cra-app polyfill, you are saying put these in the `useFetch.ts`?
```js
import 'react-app-polyfill/ie11'
import 'react-app-polyfill/stable'
```
I might just put this in the documentation. If you need ie11 support, use these polyfills. Thoughts?

**Comment by Akswii** [comment]
Correct. Yes you can do that / just have a link or reference to the react docs as they cover this if you want to be ie11 compatible.

**Comment by Akswii** [comment]
If people are going to start testing their react app on explorer then it will crash because of react issues before it reaches your fetch library.

**Comment by alex-cory** [comment]
So anyone trying to get this to work in IE, just add these lines to the top of your main/root `App.js` file.
```js
import 'react-app-polyfill/ie11'
import 'react-app-polyfill/stable'
```
